# Generated by Django 4.0.3 on 2022-04-04 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Apptp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Familiar2',
            new_name='Familiar',
        ),
        migrations.DeleteModel(
            name='Familiar1',
        ),
        migrations.DeleteModel(
            name='Familiar3',
        ),
    ]
