# Generated by Django 4.0.3 on 2022-04-13 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Apptp', '0002_rename_familiar2_familiar_delete_familiar1_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Familiar',
        ),
    ]
