# Generated by Django 4.0.3 on 2022-04-27 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Apptp', '0004_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amigos',
            name='amigo_de',
        ),
    ]
