# Generated by Django 4.0.3 on 2022-05-02 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apptp', '0006_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='familiar',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
