# Generated by Django 4.0.3 on 2022-05-02 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Apptp', '0007_familiar_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familiar',
            name='avatar',
        ),
    ]
